package me.imli.tulindemo.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import me.imli.tulindemo.MessageData;

import me.imli.tulindemo.db.MessageDataDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig messageDataDaoConfig;

    private final MessageDataDao messageDataDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        messageDataDaoConfig = daoConfigMap.get(MessageDataDao.class).clone();
        messageDataDaoConfig.initIdentityScope(type);

        messageDataDao = new MessageDataDao(messageDataDaoConfig, this);

        registerDao(MessageData.class, messageDataDao);
    }
    
    public void clear() {
        messageDataDaoConfig.clearIdentityScope();
    }

    public MessageDataDao getMessageDataDao() {
        return messageDataDao;
    }

}
